---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pod1-replicationcontroller
spec:
  replicas: 3
  selector:
    app: alpine-box
  template:
    metadata:
      name: alpine
      labels:
        app: alpine-box
    spec:
      containers:
      - name: alpine-box
        image: alpine
        command: ["sleep","3600"]
        